### ISSUE TITLE
Input file  charset  setup

### ISSUE THREAD

**Issue by shongting** [bloonix/awesant#40]
hi
    when I use this logstash ship to send my log,there had a problem with the file charset.
    My log file has Chinese,now I send messages to redis,the Chinese in file will be messy code.
    like so:  2014-12-02 15:52:028 INFO ACServer [http-bio-8080-exec-1] com.netinfo.ctrip.acserver.web.action.DeviceAction è·ååå¸­ä¿¡æ¯
    My file was utf-8 enconding,ES default the same .
    There has no charset or other method to solve this problem,pls help me,thanks.

**Comment by j-schulz** [comment]
Seems that nobody can help you :(
