### ISSUE TITLE
Loosing data if filenames are identical but path different

### ISSUE THREAD

**Issue by nv1t** [bloonix/awesant#43]
There's a chance of loosing data of the basename of two files are identical, but the path isn't.
The (experimental) feature of saving positions only works for files with different names

szenario:
/var/log/apache2/site1/access.log
/var/log/apache2/site2/access.log

save position file would be identical.

Proposal: Wouldn't it be better to use the inode as name? The inode should be unique and you can find the position file as well. Checks for rotation have to look different then.

**Comment by j-schulz** [comment]
https://github.com/bloonix/awesant/commit/0892120e6af8332f64f993ba9111f835ab388abd

Just upgrade to the latest version :-)

**Comment by j-schulz** [comment]
You can download v0.18 from https://download.bloonix.de/repos.

**Comment by j-schulz** [comment]
"Wouldn't it be better to use the inode as name?"

That's a great idea... that would prohibit the issue with too long file names.

**Comment by nv1t** [comment]
ah you are using the path as filename...didn't see that coming...
silly me...was looking through an old version, when i debugged this problem.

inodes would help, indeed...but at the moment it looks like you are checking if the inodes changes respectivaly to the filename to check for logrotates. That wouldn't be possible anymore.

**Comment by j-schulz** [comment]
Awesant now uses md5 strings instead of filenames.

Just install the latest version. Cheers.
