### ISSUE TITLE
Awesant keeps sending same line over and over.

### ISSUE THREAD

**Issue by multiservicio** [bloonix/awesant#46]
Hello,

We spent the whole day of yesterday trying to debug/catch a potential bug on awesant.
I will try to explain in the most detailed way I can :-)

Environment:
We use awesant on production machines to ship several log files in JSON from different folders on the system.
Typically about 14 million of lines per 24h. We use Ubuntu server 14.04 LTS as OS on a well known cloud provider.

Behaviour:
On one of the log files new line is inserted then awesant successfully send it over to ELK stack. No issues with this BUT after first time is sent, it continues sending the same line over and over so in the ELK stack the same line gets inserted constantly and repeately until awesant-agent on the instance gets restarted.

This behaviour only occurs under specific circumstances. The configuration of awesant for that specific folder is the following one:

```
file {
    type custom_logs
    format json
    path /var/log/shipped/custom/*json.log
}
```

The file(s) does not exists until some process log something then the file is created and the first line is added.

We enabled debug mode on awesant and we saw that awesant reads the file to create the first batch of lines to be shipped, then it reads again the file but it piles up the newer lines on top of the already sent ones.

```
  batch 1 -> 1 line
  batch 2 -> 2 lines (the first line + new line)
  batch 3 -> 3 lines (the first 2 lines + new line)
```

and so on...

This behaviour just stops if we restart the service. Then all goes back as is supposed.
Another important mention is the fact that no other log files are affected. Awesant keeps sending correctly the data of the other files on the same instance.

Quick fix:
We temporally fix this issue by ```touch``` the file before any line is appended.
Apparently if the file exists before any line is added then awesant handles it without any further problem.

More observations:
We also observed that while the wrong behaviour is happening if the log get rotated then awesant goes back to normal way and sends data correctly.
Another thing that "auto fixes it" is just touching a new file on same folder and drop a line there. Then the new file+line gets send and the "stuck" file get "unstuck".
We also tried different versions of awesant from 0.13 to current 0.18 and in all of them we see same behaviour.

Now we are wondering if awesant if having a bug or we are having issues on our configuration/set up.
We can provide logs and so on since we are able to reproduce this behaviour quite easily.

We will appreciate help in this matter since we are very happy with the overall performance of awesant.  

Thank you very much.

**Comment by j-schulz** [comment]
Hi Pedro,

that is ugly. Does this issue happends with all logfiles or only with one? Is it reproducable?

Cheers
Jonny

**Comment by j-schulz** [comment]
Ah, the current version of awesant is 0.20.

**Comment by j-schulz** [comment]
http://download.bloonix.de/repos/
http://download.bloonix.de/sources/
